version: '3.8'

services:
  
  djangoapp:
    container_name: docker
    build: 
      context: .
    command: sh -c "chmod +x migrate.sh && ./migrate.sh && ./entrypoint.sh"
    volumes:
      - .:/app
      - dev-app-data:/vol/web
    env_file:
      - .env
    ports:
      - 8001:8010
    depends_on:
      database:
         condition: service_healthy
 
  database:
    image: postgres:16.3-alpine
    container_name: database
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  dev-db-data:
  dev-app-data: