version: '3.8'

services:
  
  djangoapp:
    container_name: djangoapp
    build: 
      context: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - dev-app-data:/vol/web
    environment:
      - DEBUG=1
      - PG_HOST=database
      - PG_DB=django-dev-db
      - PG_USER=devuser
      - PG_PASSWORD=devpassword123
    ports:
      - 8000:8000
    depends_on:
      database:
         condition: service_healthy
 
  database:
    image: postgres
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django-dev-db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword123
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "django-dev-db", "-U", "devuser"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  dev-db-data:
  dev-app-data:
