apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    app: django
    tier: app
  ports:
  - port: 8000
  type: LoadBalancer


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  labels:
    app: django
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      volumes:
        - name: django-data
          persistentVolumeClaim:
            claimName: django-pvc
      containers:
        - image: django-app:latest
          imagePullPolicy: Never
          name: app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
              name: app
          volumeMounts:
            - name: django-data
              mountPath: /vol/web
          env:
            - name: POSTGRES_DB
              value: koyebdb
            - name: POSTGRES_USER
              value: koyeb-adm
            - name: POSTGRES_PASSWORD
              value: 13wqlOYPXprC
            - name: POSTGRES_HOST
              value: ep-ancient-glade-a12qjarc.ap-southeast-1.pg.koyeb.app
         
        
     