apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: django-postgres
spec:
  selector:
    matchLabels:
      app: django
      tier: postgres
    strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: myapp
        tier: postgres
    spec:
      containers:
      - name: myapp
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5432
            name: postgres
        env:
          - name: POSTGRES_DB
            value: django-dev-db
          - name: POSTGRES_USER
            value: devuser
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db_password
                key: password