# Generated by Django 5.0.6 on 2024-05-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='updated_at',
        ),
    ]
